name: "Yubico Security - Static Analysis"

on:
    workflow_call:
        inputs:
            snyk-enabled:
                description: "Whether to run Snyk test and monitor. If 'true', be sure to populate the other 'snyk-*' inputs/secrets."
                type: boolean
                required: true
            snyk-languages:
                description: "A JSON array of languages to configure for Snyk scanning."
                type: string
            snyk-org-id-or-slug:
                description: "The id or slug of the Snyk organization in which the results should be saved to. Required if Snyk scanning is enabled."
                type: string
            snyk-test-severity-threshold:
                description: "Report vulnerabilities only at the specified level or higher. One of: low, medium, high, critical. Required if Snyk scanning is enabled."
                type: string
                default: "medium"
        secrets:
            snyk-token:
                description: "A Snyk CLI/API token, ideally of a Snyk organization-level service account. Required if Snyk scanning is enabled."
                required: false

        
jobs:
    snyk:
        if: inputs.snyk-enabled
        name: "Snyk dependency scanning"
        runs-on: ubuntu-22.04
        permissions:
          # required for all workflows
          security-events: write
          # only required for workflows in private repositories
          actions: read
          contents: read
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
              with:
                persist-credentials: false

            # The following are already installed by default on the runner, so no need for a separate setup(?)
            # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
            # - .NET Core SDK (w/ NuGet)
            # - PHP (w/ Composer)
            # - Java and Kotlin  (w/ Gradle and Maven)
            # - Python (w/ pip but *not* Poetry)
            # - NodeJS (w/ npm and Yarn)

            - name: "Setup Go"
              if: contains(fromJson(inputs.snyk-languages), 'go')
              uses: actions/setup-go@v4
              with:
                go-version: stable

            - name: "Setup Snyk"
              uses: snyk/actions/setup@master

            - name: "Snyk monitor"
              run: snyk monitor --org=${{inputs.snyk-org-id-or-slug}} --all-projects --detection-depth=20 --debug --project-tags=Repo=$GITHUB_REPOSITORY
              env:
                SNYK_TOKEN: ${{ secrets.snyk-token }}

            - name: "Snyk test"
              continue-on-error: true 
              run: snyk test --org=${{inputs.snyk-org-id-or-slug}} --all-projects --detection-depth=20 --fail-on=upgradable --debug --sarif-file-output=snyk.sarif
              env:
                SNYK_TOKEN: ${{ secrets.snyk-token }}

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: snyk.sarif